{
 "title": "Planetarium",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of alerts",
   "type": "alertlist",
   "description": "This shows the total number of alerts",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 }
  },
  {
   "title": "Alerts",
   "type": "alertlist",
   "description": "This shows any alerts that we might need to look into",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 1 }
  },
  { "title": "SLI Success Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "5 minutes success rate",
   "type": "timeseries",
   "description": "This shows the average success rate within the past 5 minutes",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"planetarium-app\", status!=\"500\"}[5m])) / sum(rate(http_server_requests_seconds_count{job=\"planetarium-app\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "15 minutes success rate",
   "type": "timeseries",
   "description": "This shows the average success rate within the past 15 minutes",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"planetarium-app\", status!=\"500\"}[15m])) / sum(rate(http_server_requests_seconds_count{job=\"planetarium-app\"}[15m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "30 minutes success rate",
   "type": "timeseries",
   "description": "This shows the average success rate within the past 30 minutes",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"planetarium-app\", status!=\"500\"}[30m])) / sum(rate(http_server_requests_seconds_count{job=\"planetarium-app\"}[30m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "1 hour success rate",
   "type": "timeseries",
   "description": "This shows the average success rate within the past 1 hour",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"planetarium-app\", status!=\"500\"}[1h])) / sum(rate(http_server_requests_seconds_count{job=\"planetarium-app\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "SLI Latency Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "5 minutes latency",
   "type": "timeseries",
   "description": "This shows the average latency within the past 5 minutes",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{job=\"planetarium-app\"}[5m])) / sum(rate(http_server_requests_seconds_count{job=\"planetarium-app\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "15 minutes latency",
   "type": "timeseries",
   "description": "This shows the average latency within the past 15 minutes",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{job=\"planetarium-app\"}[15m])) / sum(rate(http_server_requests_seconds_count{job=\"planetarium-app\"}[15m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "30 minutes latency",
   "type": "timeseries",
   "description": "This shows the average latency within the past 30 minutes",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{job=\"planetarium-app\"}[30m])) / sum(rate(http_server_requests_seconds_count{job=\"planetarium-app\"}[30m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "1 hour latency",
   "type": "timeseries",
   "description": "This shows the average latency within the past 1 hour",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{job=\"planetarium-app\"}[1h])) / sum(rate(http_server_requests_seconds_count{job=\"planetarium-app\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}