loki:
  tolerations:
    - key: "monitoring"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
promtail:
  tolerations:
    - key: "monitoring"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
    - key: "application"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"