prometheus:
  prometheusSpec: 
    serviceAccountName: prometheus
    serviceMonitorNamespaceSelector: {}
    serviceMonitorSelector: 
      matchLabels:
          release: prometheus
    podMonitorSelector: {}
    # additionalScrapeConfigs:
    #   name: additional-scrape-configs
    #   key: prometheus-additional-job.yaml
    resources:
      requests:
        memory: 400Mi
    enableAdminAPI: false
    alerting:
      alertmanagers:
      - namespace: default
        name: alertmanager-operated
        port: web
    ruleSelector:
      matchLabels:
        role: alert-rules
        prometheus: socks-shop
      
grafana:
  namespaceOverride: "default"
  grafana.ini:
    server:
      serve_from_sub_path: "true"
      root_url: "%(protocol)s://%(domain)s:/grafana/" 

  ingress:
    enabled: true
    path: /grafana
    ingressClassName: nginx

alertmanager:
  config:
    global:
      resolve_timeout: 5m

    route:
      receiver: 'email'
      group_by: ['alertname']
      group_wait: 10m
      group_interval: 10m
      repeat_interval: 6h
      receiver: 'email'

      routes:
      - match:
          alertname: Watchdog
        receiver: 'null'
      - match:
          alertname: AppDown
        receiver: 'email'
        continue: true

    receivers:
    - name: 'null'
    - name: 'email'
      email_configs:
      - to: 'allan841@revature.net'
        from: 'sreteamkuberknights@gmail.com'
        smarthost: smtp.gmail.com:587
        auth_username: 'sreteamkuberknights@gmail.com'
        auth_identity: 'sreteamkuberknights@gmail.com'
        auth_password: 'xowdtptpcxljxpxz'
      - to: 'ryan819@revature.net'
        from: 'sreteamkuberknights@gmail.com'
        smarthost: smtp.gmail.com:587
        auth_username: 'sreteamkuberknights@gmail.com'
        auth_identity: 'sreteamkuberknights@gmail.com'
        auth_password: 'xowdtptpcxljxpxz'
      - to: 'abraham126@revature.net'
        from: 'sreteamkuberknights@gmail.com'
        smarthost: smtp.gmail.com:587
        auth_username: 'sreteamkuberknights@gmail.com'
        auth_identity: 'sreteamkuberknights@gmail.com'
        auth_password: 'xowdtptpcxljxpxz'
    - name: 'sns'
      sns_configs:
      - phone_number: '6092818686'


